# 站点
baseURL = 'https://hencte.top' # 请保证其链接完整性（即带有 htts://）
title = "亦幸小阁"
copyright = "版权所有"
sectionPagesMenu = "main"
languageCode = 'zh'

# 内容
defaultContentLanguage = 'zh'
hasCJKLanguage = true
enableEmoji = true
enableInlineShortcodes = true # Default value: false
enableGitInfo = true

paginate = 3

# Hugo Module:
#      hugo mod get -u
[module]
proxy = 'https://goproxy.cn'
#                                                         Vendor Name (Shorthand)
# Icon https://hugomods.com/zh-hans/icons/
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/simple-icons' # simple
