# 站点信息配置
baseURL = 'http://localhost' # 请保证其链接完整性（即带有 htts://）
title = "亦幸小阁"
copyright = "版权所有"
languageCode = 'zh'
# sectionPagesMenu = "main" # 懒得写菜单就用这个

# 内容
defaultContentLanguage = 'zh'
hasCJKLanguage = true
enableEmoji = true
enableInlineShortcodes = true # 行内简码 Default value: false
enableGitInfo = true
paginate = 10
relativeURLs = true           # 为内容开启，相对路径，而不是直接生成绝对路径，这对需要在多个域名下部署很有帮助 默认为：false

# 分类
[taxonomies]
tag = 'tags'            # 英文，首字母大写
category = 'categories' # 中文
series = 'series'       # 除非你花费了大量的时间区研究的一个东西，否则请不要为其添加 series 系列，这个相当于知乎的专栏

# 关联内容
[related]
includeNewer = true
threshold = 20
toLower = false
[[related.indices]]
name = "fragmentrefs"
type = "fragments"
applyFilter = true        # default: false
weight = 60
cardinalityThreshold = 50
[[related.indices]]
name = 'tags'
weight = 40
[[related.indices]]
name = 'categories'
weight = 50
[[related.indices]]
name = 'type'
weight = 20
[[related.indices]]
name = "date"
weight = 30


# 模块
[module] # hugo mod get -u MODULE_NAME
min = '0.111.0'              # https://gohugo.io/content-management/related/#index-content-headings-in-related-content
proxy = 'https://goproxy.cn'
