# 注意，官方的是在 pre 中使用 html 标签的方式实现菜单图标，
# 这里我们使用类或者 UnoCSS 的属性来实现，你可以在 https://icones.js.org/ 中找到你

[[main]]
name = "日志"
title = "日志"
pre = 'i-gridicons:posts'
pageRef = "/log"
identifier = "log"
weight = 1
[[main]]
name = "技术"
title = "技术"
identifier = "tech"
pre = 'i-material-symbols:edit-note-sharp'
pageRef = "/tech"
weight = 2
[[main]]
name = "关于"
title = "关于"
identifier = "about"
pre = 'i-mdi-about-circle-outline'
pageRef = "/about"
weight = 0

# [[footer]]
# title = "本站点由 Hugo 强力支持"
# name = "Hugo"
# pre = 'i-simple-icons:hugo'
# url = 'https://gohugo.io/'
# weight = 1
# [[footer]]
# title = "感谢 Github 的免费代码托管"
# name = "Github"
# pre = 'i-simple-icons:github'
# url = 'https://github.com/hencter/'
# weight = 2
# [[footer]]
# title = "感谢 Gitee 的免费代码托管"
# name = "Gitee"
# pre = 'i-simple-icons:gitee'
# url = 'https://gitee.com/hencter'
# weight = 3
