# Default Output Formats 
# ============================
# Kind          Default Output Formats
# page	        HTML
# home	        HTML, RSS
# section	      HTML, RSS
# taxonomy	    HTML, RSS
# term	        HTML, RSS


# home = ["HTML", "RSS", "JSON"]
log = ["HTML", "RSS", "JSON"]
bak = ["HTML", "RSS", "JSON"]
about = ["HTML", "RSS", "JSON"]


# SECTION  = []
# posts = ["HTML", "RSS"]
# taxonomy = ["HTML", "RSS", "JSON"]
# term = ["HTML", "RSS", "JSON"]
