#!/usr/bin/env python3
"""Audit which third-party / generated assets each rendered page pulls in.

Theme work keeps adding optional sidecars (MathJax, mermaid, Heti), and the
cheap way to keep them cheap is to check that only the pages that need them load
them. Reads the built site, so it reports what visitors actually download.

  python scripts/asset_audit.py [--public public]
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import re

# Label -> substring that identifies the asset in the HTML.
ASSETS = {
    "MathJax (math)": "mathjax@3",
    "mermaid (diagrams)": "mermaid@11",
    "Heti (古文)": "heti.min",
    "Tailwind stylesheet": "/css/tailwind",
    "demo console.log": "This site was generated by Hugo",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--public", default="public")
    args = ap.parse_args()

    root = pathlib.Path(args.public)
    pages = sorted(root.rglob("index.html"))
    if not pages:
        raise SystemExit(f"no pages under {root} — run `pnpm build` first")

    hits: dict[str, list[str]] = collections.defaultdict(list)
    for page in pages:
        html = page.read_text(encoding="utf-8", errors="ignore")
        for label, needle in ASSETS.items():
            if needle in html:
                hits[label].append(page.relative_to(root).as_posix())

    print(f"pages scanned: {len(pages)}\n")
    for label in ASSETS:
        pages_with = hits.get(label, [])
        share = len(pages_with) / len(pages) * 100
        print(f"{label:24} {len(pages_with):4d} page(s)  ({share:5.1f}%)")
        for p in pages_with[:5]:
            print(f"    {p}")
        if len(pages_with) > 5:
            print(f"    … and {len(pages_with) - 5} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
